name: 'Setup Node.js and Install Dependencies'
description: 'Setup Node.js environment and install npm dependencies'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      shell: bash
